### ISSUE TITLE
Tapo C200 camera becomes unresponsive after tried adding new scope

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [edgexfoundry-holding/device-onvif-camera#4]
Default configuration consists of all fixed scopes. In order to execute 'SetScopes', I have tried to create new scope using AddScopes API. However, adding new scope was unsuccessful and camera becomes unresponsive after that. Had to reboot Tapo C200 camera to make it work again.

**Comment by cloudxxx8** [comment]
this might be the camera specific issue
please try to contact the camera manufacturer

**Comment by brianointel** [comment]
similar issue to https://github.com/edgexfoundry-holding/device-onvif-camera/issues/24

**Comment by weichou1229** [comment]
@vyshali-chitikeshi 
Close issue because it's not the device-onvif-camera's bug. 

You can use SetScopes instead of AddScopes, I've created a PR to add the Postman collection for testing the ONVIF APIs, the doc [tested-onvif-camera](https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/tested-onvif-camera.md) also mention the AddScopes are not working on Tapo C200.
